### ISSUE TITLE
Turn Travis on in Travis website?

### ISSUE THREAD

**Issue by IainNZ** [vgupta1/DDUS.jl#1]
Seems like Travis isn't turned on on the Travis website?

**Comment by vgupta1** [comment]
So, I've turned it on on the Travis website.  Thank you for setting up the .yml script!
Fixed a small (freudian?) typo.  Still seems to be failing because it's not correctly pulling down GLPK?  

Tried googling around a little fora  solution but yet to figure it out.  Any suggestions would be appreciated.

**Comment by IainNZ** [comment]
GLPK needs a dependency that it doesn't install automatically, if I recall.

What I can't explain to you is why the JuMPeR tests pass without doing this...

**Comment by IainNZ** [comment]
Ahh a closer examination reveals that GLPK also fails to build there too, BUT I've disabled a lot of the tests while I refactor them. Good to know :D

**Comment by IainNZ** [comment]
It might fail on Julia 0.4 too - I don't test JuMPeR against it because I don't have the bandwidth, but we'll see what happens, maybe it'll pass.

**Comment by IainNZ** [comment]
Looks like tests mostly pass, seems to be an issue re: needing a QP solver?

**Comment by vgupta1** [comment]
Yes... that's on me.  The other numeric ones are something i've been
hunting for a while...

1) What do you suggest about the test requiring a QP Solver?
2) The tests with the numeric failures are on me...  There's a something
wonky in that particular numerical computation.  I will look into it.
3) Why are there tests failing but Travis still reports a (building)
success?  Do I need to edit the travis file to make it take the results
from the tests and return a non-zero value?

VG

**Comment by IainNZ** [comment]
For 3: Put `FactCheck.exitstatus()` at the very end of your tests - this will cause Julia to quit, with a non-zero error code if any facts didn't pass.

For 1: The QP solver thing might be resolved by using ECOS.jl, which Miles is working on right now in JuMP/MathProgBase - basically turning the QP into a SOCP and solving it that way using ECOS, all transparently. This is obviously not an immediate thing. There is also the idea of using IPOPT to solve QPs. All these things will be possible soon with more plumbing by us, but not yet - so maybe disable them? D:

**Comment by vgupta1** [comment]
Hi Iain

So I think this should be close-able now.  As a review:
1) I've factored out tests requiring a qp solver to "runtests_qp.jl"  Once
JuMP supports them natively, we can reintegrate
2) I've changed one of the numerical computations (removing one dependence
on Optim).  This computation required rebasing some tests
3) The travis build now seems to work on release, but fail on the nightly
build.  I have no idea why that might be.  Thoughts?

VG

**Comment by vgupta1** [comment]
More details:
The fail on the nightly build seems to be due to small (but negligibly
small) differences in some of the tests...  Do you know if one of random
number generators changed or something similar?

VG

**Comment by IainNZ** [comment]
That is odd that it changed, I know its been touched but I don't know to what degree

**Comment by IainNZ** [comment]
Just did a quick test, got the same exact numbers on 0.4 and 0.3

**Comment by IainNZ** [comment]
Maybe just disable 0.4 tests for now? I don't look at them for JuMPeR anyway

**Comment by vgupta1** [comment]
So do the tests pass or fail for you?

**Comment by IainNZ** [comment]
Sorry, I mean I get the same numbers from randn(10) on both, didn't try package.

**Comment by vgupta1** [comment]
Alright, I"ll spend some more time on this today and shut down the nightly
build if necessary.

Is there anything else this needs (beyond documentation) to get it usable
for the Robust class?

**Comment by IainNZ** [comment]
Not sure if you noticed, but JuMPeR's Travis runs DDUS.jl tests too: https://github.com/IainNZ/JuMPeR.jl/blob/master/.travis.yml
