### ISSUE TITLE
When using UCSOracle, with no support, and a cutsolver set, cutsolver is not used

### ISSUE THREAD

**Issue by IainNZ** [vgupta1/DDUS.jl#8]
I'm guessing because of something happening inside `kappa(eps_k)`?

**Comment by vgupta1** [comment]
So... this is sort of by design...  With no support, you can do things
closed-form.  It's only with support that you actually need to directly
solve an optimization.  Do you see a problem with this or the interface
design?

**Comment by IainNZ** [comment]
Ah hold on, I'm confused. I was seeing a lot of output, but I forgot I'm solving an LP, so what I was seeing is the master solving and hotstarting

**Comment by IainNZ** [comment]
Used to MIPs where there isn't much output if the cutsolver is set

**Comment by vgupta1** [comment]
Now I'm confused. :)  Do you think there is a problem or not?

**Comment by IainNZ** [comment]
No problem whatsover, I just confused myself
